mybatis:
  config-location: classpath:sql/mybatis-config.xml

spring:
  application:
    name: server

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/place_here?serverTimezone=UTC&characterEncoding=UTF-8
    #    url: jdbc:mysql://192.168.0.5:3306/place_here?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: "root"
    driver-class-name: com.mysql.cj.jdbc.Driver


# Spring Boot 내장 서버 포트 설정
server:
  port: 8080

